import Link from "next/link";
import Navbar from "@/components/Navbar";
import { prisma } from "@/lib/prisma";

export const metadata = { title: "Projects", description: "Explore selected engineering and infrastructure projects by SGR Petropower Engineering." };

export default async function ProjectsPage() {
    const projects = await prisma.project.findMany({ orderBy: { createdAt: "desc" }, include: { media: { orderBy: { sortOrder: "asc" }, take: 1 } } });
    return <main className="min-h-screen bg-slate-100"><div className="bg-slate-950"><Navbar /><section className="mx-auto max-w-7xl px-6 pb-20 pt-40 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.25em] text-[#ed1c24]">Selected work</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold tracking-tight text-white sm:text-6xl">Work that stands up to scrutiny.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">A growing record of engineering work across energy, petroleum and industrial infrastructure.</p></section></div><section className="mx-auto max-w-7xl px-6 py-20 lg:px-8">{projects.length ? <div className="grid gap-6 md:grid-cols-2">{projects.map((project) => <Link href={`/projects/${project.slug}`} key={project.id} className="group overflow-hidden rounded-2xl bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl">{project.media[0] ? <img src={project.media[0].url} alt={project.media[0].alt || project.title} className="h-72 w-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="h-72 bg-[linear-gradient(135deg,#243d4e,#0c1823)]" />}<div className="p-7"><div className="flex items-center justify-between"><span className="text-sm font-bold uppercase tracking-[0.18em] text-orange-500">{project.status}</span>{project.completionYear && <span className="text-sm text-slate-400">{project.completionYear}</span>}</div><h2 className="mt-4 text-2xl font-semibold text-slate-900">{project.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-7 text-slate-500">{project.description}</p></div></Link>)}</div> : <div className="border border-dashed border-slate-300 px-6 py-20 text-center text-slate-500">Projects will appear here once they are published from the admin workspace.</div>}</section></main>;
}