"use client";

import { useState } from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";

export default function ContactForm({ services }) {
    const [form, setForm] = useState({ fullName: "", email: "", phone: "", company: "", requestedService: "", message: "" });
    const [state, setState] = useState({ loading: false, error: "", success: false });
    function change(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
    async function submit(event) { event.preventDefault(); setState({ loading: true, error: "", success: false }); const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (response.ok) { setState({ loading: false, error: "", success: true }); setForm({ fullName: "", email: "", phone: "", company: "", requestedService: "", message: "" }); } else setState({ loading: false, error: result.error || "Unable to submit inquiry", success: false }); }
    if (state.success) return <div className="flex min-h-[480px] items-center justify-center rounded-2xl border border-emerald-200 bg-white p-8 text-center shadow-sm"><div><CheckCircle2 className="mx-auto text-emerald-500" size={48} /><h2 className="mt-6 text-3xl font-semibold text-slate-900">Inquiry received.</h2><p className="mt-3 max-w-md leading-7 text-slate-500">Thank you for reaching out. Our team will review your brief and respond as soon as possible.</p><button onClick={() => setState({ loading: false, error: "", success: false })} className="mt-8 font-semibold text-orange-600 hover:text-orange-700">Send another inquiry</button></div></div>;
    return <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Full name" name="fullName" value={form.fullName} change={change} required /><Field label="Work email" name="email" type="email" value={form.email} change={change} required /><Field label="Phone" name="phone" value={form.phone} change={change} /><Field label="Company" name="company" value={form.company} change={change} /></div><div className="mt-5"><label className="block"><span className="mb-2 block text-sm font-medium text-slate-700">Requested service</span><select name="requestedService" value={form.requestedService} onChange={change} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-orange-500"><option value="">Select a service</option>{services.map((service) => <option key={service.title}>{service.title}</option>)}</select></label></div><div className="mt-5"><Field label="Project brief" name="message" value={form.message} change={change} required textarea /></div>{state.error && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{state.error}</p>}<button disabled={state.loading} className="mt-6 flex items-center gap-2 rounded-xl bg-[#ed1c24] px-5 py-3.5 font-semibold text-white hover:bg-orange-600 disabled:opacity-60">{state.loading ? "Sending..." : "Send inquiry"}<ArrowRight size={18} /></button></form>;
}

function Field({ label, name, value, change, required, textarea, ...props }) { const Input = textarea ? "textarea" : "input"; return <label className="block"><span className="mb-2 block text-sm font-medium text-slate-700">{label}</span><Input name={name} value={value} onChange={change} required={required} rows={textarea ? 7 : undefined} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-orange-500" {...props} /></label>; }